### ISSUE TITLE
希望增加天劫修正

### ISSUE THREAD

**Issue by PaleNeutron** [kkle1994/HappyLife#1]
据说当前天劫的逻辑是地块必须被采集若干次才会触发天劫，然后再判定是否出天材地宝。

但是实际上现在地块采集的功能非常鸡肋，希望能让天劫回归随机/其他机制。比如说某个地区的外道被清理的次数之类的。

**Comment by kkle1994** [comment]
非常好的建议，但是我现在已经不太玩这个游戏了，而且最近刚刚得了新冠,体力也不如之前了。如果可以的话，你可以尝试阅读代码进行修改哦，或者等我恢复一些？

**Comment by PaleNeutron** [comment]
请问天劫在代码里的关键词是什么？有关键词的话我倒是可以自己修改。

**Comment by PaleNeutron** [comment]
已经自己新增了一个天材地宝mod来实现这个功能
